# Generated by Django 2.1.7 on 2020-11-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doviz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurlar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='kurlar',
            name='fiyat',
        ),
    ]
