# Generated by Django 3.0.8 on 2021-05-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doviz_app', '0002_auto_20201122_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurFiyatlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.IntegerField()),
                ('kur_adı', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doviz_app.Kurlar')),
            ],
        ),
    ]
