# Generated by Django 3.0.8 on 2021-05-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doviz_app', '0004_auto_20210527_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='kur_adı',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doviz_app.KurFiyatlari'),
        ),
    ]
