# Generated by Django 3.0.8 on 2021-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doviz_app', '0005_param_kur_adı'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
