# Generated by Django 3.0.8 on 2021-06-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doviz_app', '0007_wallet_wallet_kur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='kur_adı',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doviz_app.Kurlar'),
        ),
    ]
