# Generated by Django 3.0.8 on 2021-06-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doviz_app', '0008_auto_20210618_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_kur',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doviz_app.Wallet'),
        ),
    ]
